services:
  pura:
    container_name: pura
    build: .
    volumes:
    - /srv/pura/cache:/srv/pura/cache
    configs:
    - source: pura_config
      target: config.yml

configs:
  pura_config:
    content: |
      name: Office Ladies
      url: https://www.earwolf.com/episode/the-pilot/
      cache_dir: /srv/pura/cache
