services:
  pura:
    container_name: pura
    build: .
    volumes:
    - /srv/pura/cache:/srv/pura/cache
    configs:
    - source: pura_config
      target: config.yml

configs:
  pura_config:
    content: |
      name: ${PODCAST_NAME}
      url: ${SCRAPE_URL}
      cache_dir: /srv/pura/cache
