services:

  tunnel:
    container_name: pura-tunnel
    hostname: tunnel
    image: ghcr.io/qdm12/gluetun
    devices:
    - /dev/net/tun:/dev/net/tun
    env_file:
    - .env
    cap_add:
    - NET_ADMIN
    restart: unless-stopped

  pura:
    container_name: pura
    build: .
    user: ${UID}:${GID}
    volumes:
    - /srv/shared/pura:/srv/shared/pura
    environment:
      EXPECT_IP: ${EXPECT_IP}
      EXPECT_COUNTRY: ${EXPECT_COUNTRY}
      CACHE_DIR: /srv/shared/pura/cache
      OUTPUT_DIR: /srv/shared/pura/output
      SERVER_BASE: ${SERVER_BASE}
    network_mode: "service:tunnel"
    depends_on:
      tunnel:
        condition: service_healthy

  caddy:
    container_name: pura-caddy
    image: caddy:2-alpine
    user: ${UID}:${GID}
    ports:
    - "4000:80"
    volumes:
    - /srv/pura/caddy/data:/data
    - /srv/pura/caddy/config:/config
    - /srv/shared/pura/output:/srv:ro
    restart: unless-stopped
    command: caddy file-server --browse --root /srv
